Github Action to build and push x86 and arm64v8 Docker Images
sifis-home/libp2p-rust-dht pull request #25
Opened 2023-03-15 12:36 UTC by ddeguglielmo

2023-03-15 13:01 UTC, lu-zero commented on .github/workflows/cross.yaml
> +        rm cross-x86_64-unknown-linux-gnu.tar.gz
This can be omitted

2023-03-15 13:25 UTC, lu-zero approved these changes

2023-03-20 10:28 UTC, Luni-4 requested changes
Just a simple nit @ddeguglielmo

2023-03-20 10:28 UTC, Luni-4 commented on .github/workflows/cross.yaml
> +        rm cross-x86_64-unknown-linux-gnu.tar.gz
I propose to change all these lines with this pattern:

```
curl -L "https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-gnu.tar.gz" |
tar xz -C $HOME/.cargo/bin
```

2023-03-20 12:06 UTC, merged